name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]  # Add more versions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: test-env.yaml
          init-shell: >-
            bash
          cache-environment: true
          create-args: |
            python=${{ matrix.python-version }}
          post-cleanup: 'all'

      - name: Run scmap-cli-post-install-tests.sh
        shell: bash -el {0}
        run: |
          export PATH=$( pwd ):$PATH
          ./scmap-cli-post-install-tests.sh
